### ISSUE TITLE
Trying to setup EMR even if it is not configured

### ISSUE THREAD

**Issue by acirtep** [mage-ai/mage-ai#1389]
**Describe the bug**
While running the clean mage-ai service on localhost I observe in the logs that an AWS call is being initiated in order to retrieve EMR information, even though I have not enabled EMR in metadata.yaml.
```
demo_mage_app  | [E 221115 05:17:02 web:1789] Uncaught exception GET /api/clusters/emr (172.22.0.1)
demo_mage_app  |     HTTPServerRequest(protocol='http', host='localhost:6789', method='GET', uri='/api/clusters/emr', version='HTTP/1.1', remote_ip='172.22.0.1')
demo_mage_app  |     Traceback (most recent call last):
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1702, in _execute
demo_mage_app  |         result = method(*self.path_args, **self.path_kwargs)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/mage_ai/server/api/clusters.py", line 14, in get
demo_mage_app  |         clusters = emr_cluster_manager.list_clusters()
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/mage_ai/cluster_manager/aws/emr_cluster_manager.py", line 19, in list_clusters
demo_mage_app  |         clusters = list_clusters()['Clusters']
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/mage_ai/services/aws/emr/emr.py", line 128, in list_clusters
demo_mage_app  |         clusters = emr_client.list_clusters(
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
demo_mage_app  |         return self._make_api_call(operation_name, kwargs)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 921, in _make_api_call
demo_mage_app  |         http, parsed_response = self._make_request(
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 944, in _make_request
demo_mage_app  |         return self._endpoint.make_request(operation_model, request_dict)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
demo_mage_app  |         return self._send_request(request_dict, operation_model)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 198, in _send_request
demo_mage_app  |         request = self.create_request(request_dict, operation_model)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 134, in create_request
demo_mage_app  |         self._event_emitter.emit(
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
demo_mage_app  |         return self._emitter.emit(aliased_event_name, **kwargs)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
demo_mage_app  |         return self._emit(event_name, kwargs)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
demo_mage_app  |         response = handler(**kwargs)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/signers.py", line 105, in handler
demo_mage_app  |         return self.sign(operation_name, request)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/signers.py", line 189, in sign
demo_mage_app  |         auth.add_auth(request)
demo_mage_app  |       File "/usr/local/lib/python3.10/site-packages/botocore/auth.py", line 418, in add_auth
demo_mage_app  |         raise NoCredentialsError()
demo_mage_app  |     botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**To Reproduce**
1. `poetry add mage-ai`
2. `mage start`
3. In the logs you observe a call being made to AWS to list the EMR clusters

**Expected behavior**
Any AWS EMR call should be done only if configured to use EMR.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Monterey
 - Browser: firefox
 - Version: 106.0
 - mage-ai: 0.6.3

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by tommydangerous** [comment]
👀

**Comment by wangxiaoyou1993** [comment]
This issue has been fixed in version 0.6.9. Could you bump the version and check whether the issue still exists?
