### ISSUE TITLE
AttributeError: type object 'object' has no attribute 'spawn'

### ISSUE THREAD

**Issue by ZhenoSan** [mage-ai/mage-ai#2683]
Hi,  the console prints out this error on a regular interval

> ERROR:tornado.application:Uncaught exception GET /websocket/terminal?api_key=KEY_HIDDEN&token=null (::1)
> HTTPServerRequest(protocol='http', host='localhost:6789', method='GET', uri='/websocket/terminal?api_key=KEY_HIDDEN&token=null', version='HTTP/1.1', remote_ip='::1')
> Traceback (most recent call last):
>   File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\websocket.py", line 954, in _accept_connection
>     open_result = handler.open(*handler.open_args, **handler.open_kwargs)
>   File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\lib\site-packages\mage_ai\server\terminal_server.py", line 94, in open
>     self.terminal = self.term_manager.get_terminal(self.term_name, cwd=cwd)
>   File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\lib\site-packages\mage_ai\server\terminal_server.py", line 27, in get_terminal
>     term = self.new_terminal(**kwargs)
>   File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\lib\site-packages\terminado\management.py", line 220, in new_terminal
>     return PtyWithClients(argv, env, cwd)
>   File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\lib\site-packages\terminado\management.py", line 48, in __init__
>     self.ptyproc = PtyProcessUnicode.spawn(**kwargs)
> AttributeError: type object 'object' has no attribute 'spawn'

Mage is working fine but this error does get thrown routinely. 

Exact Details to replicate:

Start a project, a new project works too.
Go to Edit Pipelines on the UI, this error should start getting thrown.

OS: Windows Server 2016
Environment: Installed using pip, running on conda
Mage Version: [v0.8.78]

OS: Windows Server 2012
Environment: Installed using pip, running on conda
Mage Version: [v0.8.83]

Python 3.10.9

Tried running as Admin as well.

**Comment by thomaschung408** [comment]
Hi @ZhenoSan! Sorry that you are experiencing this error routinely. I've relayed this to our team to take a look at. Thank you for reporting this error!

**Comment by wangxiaoyou1993** [comment]
@ZhenoSan It's a little bit hard for us to debug this issue since it's on windows server 2016. Are you able to use docker to run your Mage app?

**Comment by ZhenoSan** [comment]
No but i've tried running as Admin and i still see the same error. 

Also tried running on a different server:
OS: Windows Server 2012
Environment: Installed using pip, running on conda
Mage Version: [v0.8.83]

Exact Details to replicate:
1. Start a project, a new project works too.
2. Go to Edit Pipelines on the UI, this error should start getting thrown.

**Comment by johnson-mage** [comment]
@ZhenoSan Which version of python did you create the conda virtual environment to pip install mage with? I tried recreating the issue on a Windows 10 machine, but didn't have the same issue as you come up so perhaps it's Windows Server-specific.

**Comment by ZhenoSan** [comment]
@johnson-mage Yes it seems to be Windows Server specific to me too. Works fine on Windows 11 machine.

Python 3.10.9
