### ISSUE TITLE
PostgreSQL integration pipelines sources fail to quote schema name, so fail on schemas with invalid characters

### ISSUE THREAD

**Issue by langabi** [mage-ai/mage-ai#2903]
**Describe the bug**
For a schema name with a character such as a hyphen, mage.ai isn't quoting that schema name and so the queries are failing.

**To Reproduce**
1. Integration pipeline from PostgreSQL source (to bigquery destination, but that's probably irelevant)
2. Schema name with a hyphen, "ucook-tax" in my error trace below
3. Set up the pipeline -- this works fine, and mage.ai successfully queries the schema
4. Run pipeline, get failure

**Expected behavior**
Not failing pipeline.

So clearly the schema name is being surrounded by double quotes in some places, but not everywhere.

**Trace**
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 325, in count_records

    proc.check_returncode()

  File "/usr/local/lib/python3.10/subprocess.py", line 457, in check_returncode

    raise CalledProcessError(self.returncode, self.args, self.stdout,

subprocess.CalledProcessError: Command '['python3', '/usr/local/lib/python3.10/site-packages/mage_integrations/sources/postgresql/__init__.py', '--config_json', '{"database": "ucook1", "host": "host.docker.internal", "password": "aKi9Aij,oo", "port": "5432", "schema": "ucook-tax", "username": "pcook", "replication_slot": null, "publication_name": null}', '--settings', '/home/src/default_repo/pipelines/ucook_archive_tax/data_integration_catalog.json', '--state', '/home/src/mage_data/default_repo/pipelines/ucook_archive_tax/postgresql/order_tax_addition/order_tax_addition_state.json', '--selected_streams_json', '["order_tax_addition"]', '--count_records']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 57, in initialize_state_and_runs

    block_runs = create_block_runs(pipeline_run, logger)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 112, in create_block_runs

    record_counts_by_stream = index_by(lambda x: x['id'], integration_pipeline.count_records())

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 330, in count_records

    raise Exception(message)

Exception: INFO [2023-07-03T20:36:07.083741] {"caller": "PostgreSQL", "level": "INFO", "message": "Process started.", "tags": {}, "timestamp": 1688416567, "uuid": "74480fdb61164591a67c627b77bb4ab1", "type": "LOG"}

INFO [2023-07-03T20:36:07.083973] {"caller": "PostgreSQL", "level": "INFO", "message": "Counting records for order_tax_addition started.", "tags": {"stream": "order_tax_addition"}, "timestamp": 1688416567, "uuid": "477a95b39eb947b7a530af008a7ae3a2", "type": "LOG"}

ERROR [2023-07-03T20:36:10.582290] {"caller": "PostgreSQL", "level": "EXCEPTION", "message": "PostgreSQL process failed with error syntax error at or near \"-\"

LINE 3: FROM ucook-tax.\"order_tax_addition\"

                  ^

.", "tags": {"error": "syntax error at or near \"-\"

LINE 3: FROM ucook-tax.\"order_tax_addition\"

                  ^

", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/postgresql/__init__.py\", line 276, in <module>

    main(PostgreSQL)

", "  File \"/usr/local/lib/python3.10/site-packages/singer/utils.py\", line 235, in wrapped

    return fnc(*args, **kwargs)

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 723, in main

    source.process()

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 280, in process

    errors=traceback.format_stack(),

"], "message": "Traceback (most recent call last):

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 237, in process

    count = self.count_records(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\", line 155, in count_records

    rows, rows_temp = self.__fetch_rows(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\", line 382, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 71, in load

    data = self.execute([

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 24, in execute

    data = self.execute_with_connection(connection, query_strings)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 15, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 59, in get_data_from_query_strings

    raise err

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 52, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

psycopg2.errors.SyntaxError: syntax error at or near \"-\"

LINE 3: FROM ucook-tax.\"order_tax_addition\"

                  ^

"}, "timestamp": 1688416570, "uuid": "d3717040d06642ceb01c838bed1c97ef", "type": "LOG"}

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 237, in process

    count = self.count_records(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 155, in count_records

    rows, rows_temp = self.__fetch_rows(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 382, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 71, in load

    data = self.execute([

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 24, in execute

    data = self.execute_with_connection(connection, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 15, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 59, in get_data_from_query_strings

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 52, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

psycopg2.errors.SyntaxError: syntax error at or near "-"

LINE 3: FROM ucook-tax."order_tax_addition"

                  ^

CRITICAL PostgreSQL process failed with error syntax error at or near "-"

CRITICAL LINE 3: FROM ucook-tax."order_tax_addition"

CRITICAL                   ^

CRITICAL .

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 237, in process

    count = self.count_records(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 155, in count_records

    rows, rows_temp = self.__fetch_rows(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 382, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 71, in load

    data = self.execute([

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 24, in execute

    data = self.execute_with_connection(connection, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 15, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 59, in get_data_from_query_strings

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 52, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

psycopg2.errors.SyntaxError: syntax error at or near "-"

LINE 3: FROM ucook-tax."order_tax_addition"

                  ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/postgresql/__init__.py", line 276, in <module>

    main(PostgreSQL)

  File "/usr/local/lib/python3.10/site-packages/singer/utils.py", line 235, in wrapped

    return fnc(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 723, in main

    source.process()

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 283, in process

    raise Exception(message)

Exception: PostgreSQL process failed with error syntax error at or near "-"

LINE 3: FROM ucook-tax."order_tax_addition"

                  ^

.

Stack trace

  File "/usr/local/bin/mage", line 8, in <module>
    sys.exit(app())

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore

  File "/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py", line 158, in start
    start_server(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py", line 358, in start_server
    scheduler_manager.start_scheduler()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 75, in start_scheduler
    proc.start()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 38, in run_scheduler
    LoopTimeTrigger().start()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 9, in start
    self.run()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py", line 10, in run
    schedule_all()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler.py", line 1160, in schedule_all
    initialize_state_and_runs(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 73, in initialize_state_and_runs
    logger.exception(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 26, in exception
    self.__send_message('exception', message, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 55, in __send_message
    data['error_stack'] = traceback.format_stack(),

 ```

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the issue. We'll fix it.

**Comment by langabi** [comment]
This issue is NOT fixed; I'll open a new issue as struggling to reopen this one
