### ISSUE TITLE
Salesforce -> Snowflake data integration pipeline throws errors

### ISSUE THREAD

**Issue by mattppal** [mage-ai/mage-ai#3270]
After extracting the first batch of data successfully, a user receives the following error in their Salesforce -> Snowflake data integration pipeline. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 34, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 235, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 351, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 900, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 839, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1073, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/integration/__init__.py", line 313, in _execute_block
    print_log_from_line(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/logger/utils.py", line 83, in print_log_from_line
    raise Exception(message)
Exception: 2023-08-14T13:04:00 Snowflake process failed with error 'bookmarks'. {"error": "'bookmarks'", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/snowflake/__init__.py\", line 430, in <module>
    main(Snowflake)
", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/sql/base.py\", line 362, in main
    destination.process(sys.stdin.buffer)
", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 322, in process
    errors=traceback.format_stack(),
"], "message": "Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 317, in process
    self._process(input_buffer)
  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 441, in _process
    self.__process_batch_set(
  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 496, in __process_batch_set
    bookmarks.update(state['row'][KEY_VALUE]['bookmarks'])
KeyError: 'bookmarks'
", "caller": "Snowflake", "level": "EXCEPTION", "timestamp": 1692018240, "uuid": "cec2f04e7b9049ca9072cbde25be38f3", "type": "LOG"}
```

https://mageai.slack.com/archives/C03HTTWFEKE/p1692019374112749

**Comment by Luishfs** [comment]
This issue was reported by the same User, but it is not linked to #3287.
Reopening issue for tracking purposes
