### ISSUE TITLE
Is it possible to run an integration pipeline from cli?

### ISSUE THREAD

**Issue by enricotagliani** [mage-ai/mage-ai#3533]
I'm tring to run an integration pipeline from the command line, but I'm running into this error:
```UnboundLocalError: local variable 'source_output_file_path' referenced before assignment```
The problem seems to originate from `mage_ai/data_preparation/models/block/integration/__init__.py`
Same problem tring to use the run command from a script as shown in the [Prefect integration example](https://docs.mage.ai/integrations/prefect#run-pipeline-as-a-prefect-task):
```py
import mage_ai
import os

ABSOLUTE_PATH = os.path.abspath(os.path.dirname(__file__))
project_path = os.path.join(ABSOLUTE_PATH, '/home/src/demo_project/')
pipeline_name = 'my_pipeline'

mage_ai.run(pipeline_name, project_path)
```
This is the full error message:
```
Traceback (most recent call last):
  File "/home/src/run_test.py", line 9, in <module>
    mage_ai.run(pipeline_name, project_path)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/__init__.py", line 19, in run
    ExecutorFactory.get_pipeline_executor(pipeline).execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/pipeline_executor.py", line 52, in execute
    asyncio.run(self.pipeline.execute(
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipeline.py", line 404, in execute
    await execution_task
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 146, in run_blocks
    await asyncio.gather(*upstream_tasks)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 99, in execute_and_run_tests
    await block.execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 927, in execute
    await loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 904, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 843, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1077, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/integration/__init__.py", line 97, in _execute_block
    with open(source_output_file_path, 'w') as f:
UnboundLocalError: local variable 'source_output_file_path' referenced before assignment
```
Should it be possible to run an integration pipeline outside of the web interface or it is a feature not yet implemented?

Anyway thanks for this really promising project!
Cheers,
Enrico

**Comment by wangxiaoyou1993** [comment]
Hello @enricotagliani , the data integration pipeline currently doesn't being run via the cli.

**Comment by enricotagliani** [comment]
Good, thanks!
