### ISSUE TITLE
Pyspark Kernel throwing permission error while running pyspark code using EMR 

### ISSUE THREAD

**Issue by ApurvaLokare** [mage-ai/mage-ai#3698]
**I have attached EMR cluster to pyspark kernel. While running pyspark code, today Mage is showing this error in Output:**

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/mage_ai/data_preparation/repo_manager.py", line 290, in get_variables_dir
os.makedirs(variables_dir, exist_ok=True)

File "/usr/lib64/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)

File "/usr/lib64/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: '/home/.mage_data'

**Comment by wangxiaoyou1993** [comment]
This error doesn't matter. It's already caught. https://github.com/mage-ai/mage-ai/blob/master/mage_ai/data_preparation/repo_manager.py#L289-L292
