### ISSUE TITLE
consumer configs like "max_partition_fetch_bytes" are not allowed to set manually

### ISSUE THREAD

**Issue by eminkahramanar** [mage-ai/mage-ai#4040]
Pipeline starry_scholar execution failed with error:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/websocket_server.py", line 112, in run_pipeline

    pipeline.execute_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipeline.py", line 434, in execute_sync

    StreamingPipelineExecutor(self).execute(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipeline_executor.py", line 97, in execute

    raise e

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipeline_executor.py", line 87, in execute

    self.__execute_in_python(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipeline_executor.py", line 114, in __execute_in_python

    source = SourceFactory.get_source(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sources/source_factory.py", line 31, in get_source

    return KafkaSource(config, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sources/base.py", line 21, in __init__

    self.config = self.config_class.load(config=config)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/config.py", line 47, in load

    return self(**config)

TypeError: KafkaConfig.__init__() got an unexpected keyword argument 'max_partition_fetch_bytes'

**Comment by wangxiaoyou1993** [comment]
We'll add this option to consumer config
