### ISSUE TITLE
MS SQL integration pipelines cannot handle table names containing hyphen/whitespace

### ISSUE THREAD

**Issue by PetsChoiceJG** [mage-ai/mage-ai#4286]
**Describe the bug**

Where the table name contains hyphen or white space, the integration pipeline is unable to read it as it's not enclosing in brackets for the query. E.G - To query table in SSMS, I'd use select * from [database].[schema].[table-name example]

**To Reproduce**
1. Integration pipeline from MS-SQL source to MS-SQL destination.
2. Table name contains hyphen and whitespace, as well as non alphanumeric character $. eg - [table-name$ example]. 
3. Pipeline set up works fine, can query schema and see all tables as available streams.
4. Run pipeline, fails with below error due to MS SQL syntax error "pyodbc.ProgrammingError: ('42000', \"[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)\")"

Error

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 390, in __run_in_subprocess

    proc.check_returncode()

  File "/usr/local/lib/python3.10/subprocess.py", line 457, in check_returncode

    raise CalledProcessError(self.returncode, self.args, self.stdout,

subprocess.CalledProcessError: Command '['python3', '/usr/local/lib/python3.10/site-packages/mage_integrations/sources/mssql/__init__.py', '--config_json', '{"database": "Production", "host": "000.000.00.00", "port": "1433", "username": "PYTHON_READER", "password": "password_example", "schema": "dbo"}', '--settings', '/home/src/[project_name]/pipelines/starry_pine/data_integration_catalog.json', '--state', '/home/src/mage_data/[project_name]/pipelines/starry_pine/mssql/live_company_examplesales_line437dbf0e_84ff_417a_965d_ed2bb9650972/live_company_example_sales_line_437dbf0e_84ff_417a_965d_ed2bb9650972_state.json', '--selected_streams_json', '["LIVE-company example$Sales Line$437dbf0e-84ff-417a-965d-ed2bb9650972"]', '--count_records']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 80, in initialize_state_and_runs

    block_runs = create_block_runs(pipeline_run, logger, variables=variables)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 144, in create_block_runs

    record_counts_by_stream = index_by(lambda x: x['id'], integration_pipeline.count_records())

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 319, in count_records

    self.__run_in_subprocess(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 398, in __run_in_subprocess

    raise Exception(filter_out_config_values(message, config))

Exception: INFO [2024-01-03T12:07:36.997298] {"caller": "MSSQL", "level": "INFO", "message": "Process started.", "tags": {}, "timestamp": 1704283656, "uuid": "4bd90374a1d6476e97ed084c0b6e6875", "type": "LOG"}

INFO [2024-01-03T12:07:36.997583] {"caller": "MSSQL", "level": "INFO", "message": "Counting records for LIVE-company example$Sales Line$437dbf0e-84ff-417a-965d-ed2bb9650972 started.", "tags": {"stream": "LIVE-company example$Sales Line$437dbf0e-84ff-417a-965d-ed2bb9650972"}, "timestamp": 1704283656, "uuid": "e7073d8f7ef74baab23f71caa89124cf", "type": "LOG"}

ERROR [2024-01-03T12:07:37.024384] {"caller": "MSSQL", "level": "EXCEPTION", "message": "MSSQL process failed with error ('42000', \"[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)\").", "tags": {"error": "('42000', \"[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)\")", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/mssql/__init__.py\", line 82, in <module>

    main(MSSQL)

", "  File \"/usr/local/lib/python3.10/site-packages/singer/utils.py\", line 235, in wrapped

    return fnc(*args, **kwargs)

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 723, in main

    source.process()

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 280, in process

    errors=traceback.format_stack(),

"], "message": "Traceback (most recent call last):

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 237, in process

    count = self.count_records(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\", line 166, in count_records

    rows, rows_temp = self.__fetch_rows(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\", line 414, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 72, in load

    data = self.execute([

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 25, in execute

    data = self.execute_with_connection(connection, query_strings)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 16, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 60, in get_data_from_query_strings

    raise err

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 53, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

pyodbc.ProgrammingError: ('42000', \"[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)\")

"}, "timestamp": 1704283657, "uuid": "8d28563a0471489ba01d51244c712553", "type": "LOG"}

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 237, in process

    count = self.count_records(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 166, in count_records

    rows, rows_temp = self.__fetch_rows(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 414, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 72, in load

    data = self.execute([

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 25, in execute

    data = self.execute_with_connection(connection, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 16, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 60, in get_data_from_query_strings

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 53, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)")

CRITICAL MSSQL process failed with error ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)").

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 237, in process

    count = self.count_records(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 166, in count_records

    rows, rows_temp = self.__fetch_rows(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 414, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 72, in load

    data = self.execute([

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 25, in execute

    data = self.execute_with_connection(connection, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 16, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 60, in get_data_from_query_strings

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 53, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/mssql/__init__.py", line 82, in <module>

    main(MSSQL)

  File "/usr/local/lib/python3.10/site-packages/singer/utils.py", line 235, in wrapped

    return fnc(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 723, in main

    source.process()

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 283, in process

    raise Exception(message)

Exception: MSSQL process failed with error ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW)").

Stack trace

  File "/usr/local/bin/mage", line 8, in <module>
    sys.exit(app())

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore

  File "/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py", line 163, in start
    start_server(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py", line 632, in start_server
    scheduler_manager.start_scheduler()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 75, in start_scheduler
    proc.start()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 38, in run_scheduler
    LoopTimeTrigger().start()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 14, in start
    self.run()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py", line 11, in run
    schedule_all()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1544, in schedule_all
    PipelineScheduler(r).start()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 143, in func_with_rollback
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 148, in start
    initialize_state_and_runs(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 92, in initialize_state_and_runs
    logger.exception(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 30, in exception
    self.__send_message('exception', message, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 59, in __send_message
    data['error_stack'] = traceback.format_stack(),

**Expected behavior**
For the integration pipeline to run normally and query the relevant records from the source table.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Smartphone (please complete the following information):**
 - Version 121

**Additional context**

**Comment by PetsChoiceJG** [comment]
To add it appears there might be a problem also with the "$" symbol being present in the table names. The symbol seems to be edited out of the table name in the query.
