### ISSUE TITLE
[BUG] server hang waiting for http request response

### ISSUE THREAD

**Issue by woday-dev** [mage-ai/mage-ai#4556]
### Mage version

0.9.63

### Describe the bug

In local enviroment without network connetion.
use pip installed version.
when start the server, it's stucked at "http request sent; waiting for response"

### To reproduce

1. mage init xxx
2. mage start xxx

### Operating system

- Centos

**Comment by woday-dev** [comment]
After ^c, it stops here
Process Process-2:
Traceback (most recent call last):
  File "/anaconda/anaconda3-2022.05/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/anaconda/anaconda3-2022.05/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)
  File "/site-packages/mage_ai/server/scheduler_manager.py", line 50, in run_scheduler
    LoopTimeTrigger().start()
  File "/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 18, in start
    time.sleep(sleep_time)
KeyboardInterrupt

**Comment by wangxiaoyou1993** [comment]
The Mage server might not work without internet connection now. We'll fix that.

**Comment by dy46** [comment]
hey @woday-dev, is this a fresh install of mage? do you have any environment variables set or any other customizations? i'm able to get a Mage server running with no internet connection

**Comment by wangxiaoyou1993** [comment]
Another user got this error when running Mage without internet in docker:
![image](https://github.com/mage-ai/mage-ai/assets/80284865/3ff40fa9-c664-4620-bd53-8afacd38be00)

**Comment by woday-dev** [comment]
> hey @woday-dev, is this a fresh install of mage? do you have any environment variables set or any other customizations? i'm able to get a Mage server running with no internet connection

Hi @dy46 , yes it's a fresh install of mage via pip, virtualenv is used and no special setting by intention. Great to know it can work under no internet connetion, maybe you have internet connection the first several startup?
