### ISSUE TITLE
Trigger pipeline from block returns syntax error

### ISSUE THREAD

**Issue by sandeepdevagiri** [mage-ai/mage-ai#4700]
Here is the code I am trying to run

from mage_ai.orchestration.triggers.api import trigger_pipeline

@custom
trigger_pipeline(
    'load_loans',
    variables={},
    check_status=False,
    error_on_failure=False,
    poll_interval=60,
    poll_timeout=None,
    schedule_name=None,  # Enter a unique name to create a new trigger each time
    verbose=True,
)

And I am getting syntax error. Here is the error trace

Error

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute

    result = __execute_with_retry()

             ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/mage_ai/shared/retry.py", line 54, in retry_func

    raise e

  File "/usr/local/lib/python3.11/site-packages/mage_ai/shared/retry.py", line 38, in retry_func

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry

    return self._execute(

           ^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute

    result = self.block.execute_sync(

             ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1315, in execute_sync

    raise err

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1224, in execute_sync

    output = self.execute_block(

             ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1530, in execute_block

    outputs = self._execute_block(

              ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1658, in _execute_block

    exec(self.content, results)

  File "<string>", line 4

    trigger_pipeline(

    ^^^^^^^^^^^^^^^^

SyntaxError: invalid syntax

Stack trace

  File "/usr/local/bin/mage", line 8, in <module>
    sys.exit(app())

  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(

  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore

  File "/usr/local/lib/python3.11/site-packages/mage_ai/cli/main.py", line 163, in start
    start_server(

  File "/usr/local/lib/python3.11/site-packages/mage_ai/server/server.py", line 713, in start_server
    scheduler_manager.start_scheduler()

  File "/usr/local/lib/python3.11/site-packages/mage_ai/server/scheduler_manager.py", line 87, in start_scheduler
    proc.start()

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/server/scheduler_manager.py", line 50, in run_scheduler
    LoopTimeTrigger().start()

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 14, in start
    self.run()

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/triggers/time_trigger.py", line 11, in run
    schedule_all()

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1609, in schedule_all
    PipelineScheduler(r).start()

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/db/__init__.py", line 157, in func_with_rollback
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 190, in start
    self.schedule()

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/db/__init__.py", line 157, in func_with_rollback
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 323, in schedule
    self.__schedule_blocks(block_runs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 599, in __schedule_blocks
    job_manager.add_job(

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/job_manager.py", line 27, in add_job
    self.queue.enqueue(job_id, target, *args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/queue/process_queue.py", line 108, in enqueue
    self.start_worker_pool()

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/queue/process_queue.py", line 183, in start_worker_pool
    self.worker_pool_proc.start()

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/queue/process_queue.py", line 288, in poll_job_and_execute
    worker.start()

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.11/site-packages/newrelic/api/background_task.py", line 117, in wrapper
    return wrapped(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/queue/process_queue.py", line 253, in run
    start_session_and_run(args[1], *args[2], **args[3])

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1154, in run_block
    ).execute(

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 615, in execute
    self.logger.exception(

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/logging/logger.py", line 30, in exception
    self.__send_message('exception', message, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/mage_ai/data_preparation/logging/logger.py", line 65, in __send_message
    data['error_stack'] = traceback.format_stack(),

**Comment by wangxiaoyou1993** [comment]
you need to put the code in a method

```python
from mage_ai.orchestration.triggers.api import trigger_pipeline

@custom
def transform_custom(*args, **kwargs):
    """
    args: The output from any upstream parent blocks (if applicable)

    Returns:
        Anything (e.g. data frame, dictionary, array, int, str, etc.)
    """
    # Specify your custom logic here

    trigger_pipeline(
      'load_loans',
      variables={},
      check_status=False,
      error_on_failure=False,
      poll_interval=60,
      poll_timeout=None,
      schedule_name=None, # Enter a unique name to create a new trigger each time
      verbose=True,
    )
```

**Comment by wangxiaoyou1993** [comment]
Try the suggested fix and let me know if you still have this issue.

**Comment by sandeepdevagiri** [comment]
Yes it worked. thanks
