### ISSUE TITLE
[BUG] Failed to run scheduler (logs).

### ISSUE THREAD

**Issue by iamsabin** [mage-ai/mage-ai#4756]
### Mage version

0.9.65

### Describe the bug

The error logs mentioned below are popping up in the mage server, saying failed to run scheduler. There are no triggers or pipeline that I ran when the logs appeared. Mage and pipelines are running fine. The error logs are appearing out of nowhere.

### To reproduce

1. Just keep the mage server running for a while. It happened 2 times in the last 7 days.

### Expected behavior

No error logs that are not explainable

### Operating system

- Mage container running in Amazon ECS

### Additional context

```Failed to run scheduler.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 50, in run_scheduler
    LoopTimeTrigger().start()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 14, in start
    self.run()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py", line 11, in run
    schedule_all()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1425, in schedule_all
    sync_schedules(list(repo_pipelines))
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1791, in sync_schedules
    PipelineSchedule.create_or_update_batch(trigger_configs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 165, in func_with_rollback
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 157, in func_with_rollback
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/models/schedules.py", line 364, in create_or_update_batch
    existing_trigger.update(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/models/base.py", line 93, in update
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/models/base.py", line 90, in update
    self.session.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 839, in commit
    trans.commit()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2469, in commit
    self._do_commit()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2659, in _do_commit
    self._connection_commit_impl()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2630, in _connection_commit_impl
    self.connection._commit_impl()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1096, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by iamsabin** [comment]
Thanks @wangxiaoyou1993 , but we are not using sqlite at the moment.

We are using AWS managed MYSQL server.

Also, just before the error, it seems like there are two info logs:

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

**Comment by wangxiaoyou1993** [comment]
@iamsabin the log shows you're using sqlite. that's the default database if you don't specify the MAGE_DATABASE_CONNECTION_URL env variable

**Comment by iamsabin** [comment]
thank you so much @wangxiaoyou1993 There was one sneaky error, while setting up AWS secrets.

I will close the issue.
