### ISSUE TITLE
[BUG] Error creating default roles and permissions

### ISSUE THREAD

**Issue by frheinze** [mage-ai/mage-ai#4805]
### Mage version

v0.9.67

### Describe the bug

After enabling user authentication in a new environment (REQUIRE_USER_AUTHENTICATION=1), I get an error when creating the default roles and permissions. I get the following error message in the log: 

2024-03-21 18:04:57 HTTPServerRequest(protocol='http', host='localhost:6789', method='POST', uri='/api/seeds?api_key=ABC', version='HTTP/1.1', remote_ip='172.21.0.1')
2024-03-21 18:04:57 Traceback (most recent call last):
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
2024-03-21 18:04:57     result = await result
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/server/api/v1.py", line 64, in post
2024-03-21 18:04:57     return await execute_operation(self, resource)
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/views.py", line 63, in execute_operation
2024-03-21 18:04:57     raise err
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/views.py", line 56, in execute_operation
2024-03-21 18:04:57     response = await base_operation.execute()
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/operations/base.py", line 92, in execute
2024-03-21 18:04:57     result = await self.__executed_result()
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/operations/base.py", line 459, in __executed_result
2024-03-21 18:04:57     return await self.__create_or_index()
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/operations/base.py", line 511, in __create_or_index
2024-03-21 18:04:57     result = await self.__resource_class().process_create(
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/resources/BaseResource.py", line 186, in process_create
2024-03-21 18:04:57     raise err
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/resources/BaseResource.py", line 174, in process_create
2024-03-21 18:04:57     res = await res
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/api/resources/SeedResource.py", line 9, in create
2024-03-21 18:04:57     await bootstrap_permissions()
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/authentication/permissions/seed.py", line 241, in bootstrap_permissions
2024-03-21 18:04:57     action_rules_mapping[model_name] = await action_rules(policy_class)
2024-03-21 18:04:57   File "/usr/local/lib/python3.10/site-packages/mage_ai/authentication/permissions/seed.py", line 174, in action_rules
2024-03-21 18:04:57     condition = config2.get('condition')
2024-03-21 18:04:57 AttributeError: 'list' object has no attribute 'get'

### To reproduce

1. Activate user authentication (REQUIRE_USER_AUTHENTICATION=1)
2. Go to project settings > roles
3. Click on "Create default roles and permissions"

**Comment by dy46** [comment]
This issue should be resolved in the next version of Mage (>= 0.9.69)
