### ISSUE TITLE
[BUG] Oracle DB data integration not working

### ISSUE THREAD

**Issue by amukhsimov** [mage-ai/mage-ai#4969]
### Mage version

v0.9.69

### Describe the bug

Hi!

I am trying to setup data integration between Oracle DB (source) and Postgres (destination). I specify connection details, select the streams. But when I press "Test connection" it says:
```
Failed to connect, see error below.
ORA-00942: table or view does not exist
```

Further, I save the Pipeline, run it and the same error. It can't pull the data. Logs are attached below.

### To reproduce

1. Create new pipeline (select data integration).
2. Select Oracle DB as a source, specify connection details.
3. Press "Test connection", and here the error comes out.
4. Select streams to integrate.
5. Specify destination.
6. Run the pipeline (also the same error).

### Additional context

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 390, in __run_in_subprocess

    proc.check_returncode()

  File "/usr/local/lib/python3.10/subprocess.py", line 457, in check_returncode

    raise CalledProcessError(self.returncode, self.args, self.stdout,

subprocess.CalledProcessError: Command '['python3', '/usr/local/lib/python3.10/site-packages/mage_integrations/sources/oracledb/__init__.py', '--config_json', '{"host": "172.19.50.4", "port": "1521", "service": "FLEXPROD", "password": "DWH_RO", "user": "DWH", "schema": "OCIUZ", "mode": "thin"}', '--settings', '/home/src/dwh/pipelines/flex2dwh/data_integration_catalog.json', '--state', '/home/src/mage_data/dwh/pipelines/flex2dwh/oracledb/sttm_reportlines_custom/sttm_reportlines_custom_state.json', '--selected_streams_json', '["STTM_REPORTLINES_CUSTOM"]', '--count_records']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 160, in start

    initialize_state_and_runs(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 98, in initialize_state_and_runs

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 80, in initialize_state_and_runs

    block_runs = create_block_runs(pipeline_run, logger, variables=variables)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/utils/scheduler.py", line 144, in create_block_runs

    record_counts_by_stream = index_by(lambda x: x['id'], integration_pipeline.count_records())

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 319, in count_records

    self.__run_in_subprocess(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipelines/integration_pipeline.py", line 398, in __run_in_subprocess

    raise Exception(filter_out_config_values(message, config))

Exception: INFO [2024-04-22T10:12:09.830553] {"caller": "OracleDB", "level": "INFO", "message": "Process started.", "tags": {}, "timestamp": 1713780729, "uuid": "124428d74cab4eb889bc4f9efc0d44cc", "type": "LOG"}

INFO [2024-04-22T10:12:09.830772] {"caller": "OracleDB", "level": "INFO", "message": "Counting records for STTM_REPORTLINES_CUSTOM started.", "tags": {"stream": "STTM_REPORTLINES_CUSTOM"}, "timestamp": 1713780729, "uuid": "1e23b8ccd2fb48de8a331fb33978dcca", "type": "LOG"}

ERROR [2024-04-22T10:12:09.864057] {"caller": "OracleDB", "level": "EXCEPTION", "message": "OracleDB process failed with error ORA-00942: table or view does not exist.", "tags": {"error": "ORA-00942: table or view does not exist", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/oracledb/__init__.py\", line 152, in <module>

    main(OracleDB)

", "  File \"/usr/local/lib/python3.10/site-packages/singer/utils.py\", line 235, in wrapped

    return fnc(*args, **kwargs)

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 732, in main

    source.process()

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 281, in process

    errors=traceback.format_stack(),

"], "message": "Traceback (most recent call last):

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 238, in process

    count = self.count_records(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\", line 166, in count_records

    rows, rows_temp = self.__fetch_rows(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\", line 414, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 94, in load

    data = self.execute([

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 46, in execute

    data = self.execute_with_connection(connection, query_strings)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 16, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 82, in get_data_from_query_strings

    raise err

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\", line 75, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

  File \"/usr/local/lib/python3.10/site-packages/oracledb/cursor.py\", line 378, in execute

    impl.execute(self)

  File \"src/oracledb/impl/thin/cursor.pyx\", line 138, in oracledb.thin_impl.ThinCursorImpl.execute

  File \"src/oracledb/impl/thin/protocol.pyx\", line 382, in oracledb.thin_impl.Protocol._process_single_message

  File \"src/oracledb/impl/thin/protocol.pyx\", line 383, in oracledb.thin_impl.Protocol._process_single_message

  File \"src/oracledb/impl/thin/protocol.pyx\", line 376, in oracledb.thin_impl.Protocol._process_message

oracledb.exceptions.DatabaseError: ORA-00942: table or view does not exist

"}, "timestamp": 1713780729, "uuid": "6c497028b17145dfa1e302765ae1eb1d", "type": "LOG"}

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 238, in process

    count = self.count_records(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 166, in count_records

    rows, rows_temp = self.__fetch_rows(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 414, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 94, in load

    data = self.execute([

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 46, in execute

    data = self.execute_with_connection(connection, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 16, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 82, in get_data_from_query_strings

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 75, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

  File "/usr/local/lib/python3.10/site-packages/oracledb/cursor.py", line 378, in execute

    impl.execute(self)

  File "src/oracledb/impl/thin/cursor.pyx", line 138, in oracledb.thin_impl.ThinCursorImpl.execute

  File "src/oracledb/impl/thin/protocol.pyx", line 382, in oracledb.thin_impl.Protocol._process_single_message

  File "src/oracledb/impl/thin/protocol.pyx", line 383, in oracledb.thin_impl.Protocol._process_single_message

  File "src/oracledb/impl/thin/protocol.pyx", line 376, in oracledb.thin_impl.Protocol._process_message

oracledb.exceptions.DatabaseError: ORA-00942: table or view does not exist

CRITICAL OracleDB process failed with error ORA-00942: table or view does not exist.

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 238, in process

    count = self.count_records(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 166, in count_records

    rows, rows_temp = self.__fetch_rows(

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py", line 414, in __fetch_rows

    rows_temp = self.build_connection().load(with_limit_query_string)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 94, in load

    data = self.execute([

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 46, in execute

    data = self.execute_with_connection(connection, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 16, in execute_with_connection

    return self.get_data_from_query_strings(cursor, query_strings)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 82, in get_data_from_query_strings

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py", line 75, in get_data_from_query_strings

    cursor.execute(clean_query(query_string))

  File "/usr/local/lib/python3.10/site-packages/oracledb/cursor.py", line 378, in execute

    impl.execute(self)

  File "src/oracledb/impl/thin/cursor.pyx", line 138, in oracledb.thin_impl.ThinCursorImpl.execute

  File "src/oracledb/impl/thin/protocol.pyx", line 382, in oracledb.thin_impl.Protocol._process_single_message

  File "src/oracledb/impl/thin/protocol.pyx", line 383, in oracledb.thin_impl.Protocol._process_single_message

  File "src/oracledb/impl/thin/protocol.pyx", line 376, in oracledb.thin_impl.Protocol._process_message

oracledb.exceptions.DatabaseError: ORA-00942: table or view does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/oracledb/__init__.py", line 152, in <module>

    main(OracleDB)

  File "/usr/local/lib/python3.10/site-packages/singer/utils.py", line 235, in wrapped

    return fnc(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 732, in main

    source.process()

  File "/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py", line 284, in process

    raise Exception(message)

Exception: OracleDB process failed with error ORA-00942: table or view does not exist.

Stack trace

  File "/usr/local/bin/mage", line 8, in <module>
    sys.exit(app())

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore

  File "/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py", line 163, in start
    start_server(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py", line 750, in start_server
    scheduler_manager.start_scheduler()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 92, in start_scheduler
    proc.start()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 53, in run_scheduler
    LoopTimeTrigger().start()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 14, in start
    self.run()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py", line 11, in run
    schedule_all()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1626, in schedule_all
    PipelineScheduler(r).start()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 157, in func_with_rollback
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 169, in start
    self.logger.exception(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 30, in exception
    self.__send_message('exception', message, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 65, in __send_message
    data['error_stack'] = traceback.format_stack(),
```

**Comment by amukhsimov** [comment]
Hello!

I think I found the problem. In mage_integrations/mage_integrations/sources/oracledb/__init__.py when mage discovers the schema it doesn't consider table owner (schema) (screenshot 1).

Then in mage_integrations/mage_integrations/sources/sql/base.py discover function, it passes stream_id as tap_stream_id to __fetch_rows function (whereas stream_id is only a TABLE_NAME).

__fetch_rows uses build_table_name function, which returns f'{self.table_prefix}{table_name}', whereas self.table_prefix returns '' (empty string)

Can we add the schema to the Oracle source (data integration)?

![image](https://github.com/mage-ai/mage-ai/assets/58040807/bb34d52c-1bbb-4179-9434-9a98d928175b)
![image](https://github.com/mage-ai/mage-ai/assets/58040807/2d2feb68-e918-4586-bdf6-1c9621cc8d11)
![image](https://github.com/mage-ai/mage-ai/assets/58040807/b384bff4-92b9-4fe5-b139-9997a7f8ae06)

**Comment by AlekHed** [comment]
I have the same problem. Oracle DB integration has some weak points: 

1. It uses "SELECT name FROM v$database" query for testing connection. User need to have "GRANT SELECT ANY DICTIONARY TO user" for this query to work. Better solution imo is to use something like "select sys_context( 'userenv', 'current_schema' ) from dual" query.

2. Its possible to define schema for connection if you redefine property table_prefix in OracleDB class. I set it to read schema from self.config['schema'] if it exists in my local version. It could solve 90% problems with schemas. But most correct solution of course is to use schema from table definition.

3. For Oracle  versions prior to 12 _limit_query_string makes incorrect query string. Feels like connector need parameter to support old version recipe. But its complex modification. Need more hooks to query at sql base class.
