### ISSUE TITLE
[BUG] pipeline run failed，job_manager = null

### ISSUE THREAD

**Issue by yanlingsishao** [mage-ai/mage-ai#4999]
### Mage version

python3.9

### Describe the bug

When starting the program, the following error will be reported: successfully block the pipeline separately, but the pipeline run will fail
```
(.venv) PS D:\code\pycode\mage\mage> mage start demo1
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
INFO:mage_ai.server.scheduler_manager:Start scheduler.
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001933ED5D0D0>
Traceback (most recent call last):
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close  
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon  
    self._check_closed()
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Checking port 6789 on host localhost...
Traceback (most recent call last):
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\job_manager.py", line 99, in <module>
    job_manager = JobManager()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\job_manager.py", line 15, in __init__
    self.queue = QueueFactory.get_queue()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\queue\queue_factory.py", line 19, in get_queue
    self.queue = ProcessQueue(queue_config)
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\queue\process_queue.py", line 66, in __init__ 
    self.mp_manager = Manager()
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 57, in Manager     
    m.start()
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\managers.py", line 553, in start
    self._process.start()
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
INFO:mage_ai.server.server:Mage is running at http://localhost:6789 and serving project D:\code\pycode\mage\mage\demo1
INFO:mage_ai.server.server:Initializing block cache.
INFO:mage_ai.server.server:Initializing pipeline cache.
INFO:tornado.access:304 GET / (::1) 2.00ms
INFO:mage_ai.server.server:Initializing tag cache.
INFO:mage_ai.server.server:Initializing block action object cache.
[WARNING] SSH tunnel failed to create and connect: No module named 'sshtunnel'
INFO:mage_ai.api.logging:[2024-04-28T02:47:42.815601][api.views] Action: list statuses None  
INFO:mage_ai.api.logging:[2024-04-28T02:47:42.816599][api.views] Latency: 0.0590 seconds
INFO:tornado.access:304 GET /api/statuses?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 59.99ms
INFO:tornado.access:200 GET /favicon.ico (::1) 588.27ms
INFO:mage_ai.api.logging:[2024-04-28T02:47:44.050014][api.views] Action: list pipeline_runs None  
INFO:mage_ai.api.logging:[2024-04-28T02:47:44.051005][api.views] Latency: 0.0944 seconds
INFO:tornado.access:304 GET /api/pipeline_runs?_limit=50&include_pipeline_type=1&order_by[]=created_at%20desc&start_timestamp=1714262400&status=failed&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 96.36ms
Query: 0.005
Mapping: 0.025
Loop: 0.0
INFO:mage_ai.api.logging:[2024-04-28T02:47:44.125115][api.views] Action: detail monitor_stats pipeline_run_count  
INFO:mage_ai.api.logging:[2024-04-28T02:47:44.125115][api.views] Latency: 0.0731 seconds
INFO:tornado.access:304 GET /api/monitor_stats/pipeline_run_count?group_by_pipeline_type=1&start_time=2024-04-28T00:00:00.000Z&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 171.43ms
INFO:mage_ai.api.logging:[2024-04-28T02:47:45.052920][api.views] Action: list projects None  
INFO:mage_ai.api.logging:[2024-04-28T02:47:45.053925][api.views] Latency: 2.2353 seconds
INFO:tornado.access:304 GET /api/projects?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 2236.33ms
INFO:mage_ai.api.logging:[2024-04-28T02:47:45.701585][api.views] Action: list statuses None  
INFO:mage_ai.api.logging:[2024-04-28T02:47:45.702584][api.views] Latency: 0.0440 seconds
INFO:tornado.access:304 GET /api/statuses?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 46.01ms
INFO:alembic.runtime.migration:Context impl SQLiteImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
INFO:mage_ai.orchestration.pipeline_scheduler_original:Active pipeline runs: []
ERROR:mage_ai.server.scheduler_manager:Failed to run scheduler.
Traceback (most recent call last):
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\server\scheduler_manager.py", line 53, in run_scheduler
    LoopTimeTrigger().start()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\triggers\loop_time_trigger.py", line 14, in start
    self.run()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\triggers\time_trigger.py", line 11, in run
    schedule_all()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\pipeline_scheduler_original.py", line 1659, in schedule_all
    job_manager.clean_up_jobs()
AttributeError: 'NoneType' object has no attribute 'clean_up_jobs'
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\wang.qiyuan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\db\process.py", line 15, in start_session_and_run
    results = target(*args)
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\server\scheduler_manager.py", line 58, in run_scheduler
    raise e
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\server\scheduler_manager.py", line 53, in run_scheduler
    LoopTimeTrigger().start()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\triggers\loop_time_trigger.py", line 14, in start
    self.run()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\triggers\time_trigger.py", line 11, in run
    schedule_all()
  File "D:\code\pycode\mage\mage\.venv\lib\site-packages\mage_ai\orchestration\pipeline_scheduler_original.py", line 1659, in schedule_all
    job_manager.clean_up_jobs()
AttributeError: 'NoneType' object has no attribute 'clean_up_jobs'

```

**Comment by wangxiaoyou1993** [comment]
@yanlingsishao this is fixed in version 0.9.70
