### ISSUE TITLE
[BUG] Integration destination (python) block throws exception "Required key stream is missing from row"

### ISSUE THREAD

**Issue by kjartang5** [mage-ai/mage-ai#5104]
### Mage version

alpha build

### Describe the bug

Using integration source (python) and integration destination (python) in a standard batch pipeline.

Source block runs fine i.e. fetches data from MSSQL source and then destination block MSSQL throws the following exception:

Exception: 2024-05-13T15:51:16 Required key stream is missing from row.

I have checked whether the data streams are stored on the Fileshare drive and they seem to be, although I am not 100% sure where exactly to look and what the expected file structure is.

### Expected behavior

I expect the destination block to be able to read the data streams from disk and export them to destination.

### Screenshots

<img width="1568" alt="Screenshot 2024-05-13 at 21 51 36" src="https://github.com/mage-ai/mage-ai/assets/157366414/38fc22f8-39cb-479b-adde-5b6db443386f">
<img width="1576" alt="Screenshot 2024-05-13 at 21 54 53" src="https://github.com/mage-ai/mage-ai/assets/157366414/50304e79-2278-43cb-9240-bf380b33027f">
<img width="1556" alt="Screenshot 2024-05-13 at 21 56 25" src="https://github.com/mage-ai/mage-ai/assets/157366414/012c8b83-d3aa-4000-90d8-85db7f620f96">
<img width="1120" alt="Screenshot 2024-05-13 at 23 25 26" src="https://github.com/mage-ai/mage-ai/assets/157366414/7cd1ee21-be8f-4203-bae5-6490030d582b">

### Operating system

Running docker alpha build on infrastructure template provided for Azure i.e. mage is running on a container instance.

### Additional context

``Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute

    result = __execute_with_retry()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func

    raise e

  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry

    return self._execute(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute

    result = self.block.execute_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1261, in execute_sync

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1170, in execute_sync

    output = self.execute_block(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1476, in execute_block

    outputs = self._execute_block(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1568, in _execute_block

    return execute_data_integration(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/data_integration/utils.py", line 577, in execute_data_integration

    proc = __execute_destination(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/data_integration/utils.py", line 1036, in __execute_destination

    print_log_from_line(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/logger/utils.py", line 83, in print_log_from_line

    raise Exception(message)

Exception: 2024-05-13T17:15:45 Required key stream is missing from row. {"row_type": "LOG", "schema": {"properties": {}}, "caller": "MSSQL", "level": "EXCEPTION", "timestamp": 1715620545, "uuid": "866eb2f90b824a888ebc203ebed85e60", "type": "LOG"}``

**Comment by LDuarte-aba** [comment]
Same  error with version 0.9.70  when using **Postgres** as destination in **batch data integration pipelines**. I think the problem is related to Mage automatically changing stream names to lower case. 

In your case @kjartang5  plaio_HistoricalSales is transformed by mage to plaio_historicalsales and this name is not present in the catalog (inside the catalog it has the original uppercase letters). I have tried to override this in selected_streams on destination block but it does not work.

![image](https://github.com/mage-ai/mage-ai/assets/154368015/11df493f-2c0e-4526-9485-6623cfb30250)

If the name is in lowercase everything works
![image](https://github.com/mage-ai/mage-ai/assets/154368015/3fccc632-78e0-4864-ab03-c33926caf591)
 
 But it will fail for uppercase STREAMS
 ![image](https://github.com/mage-ai/mage-ai/assets/154368015/4948ec6a-d22c-4bf6-aa6d-d4a9857d26b4)
