### ISSUE TITLE
[BUG] integer division or modulo by zero

### ISSUE THREAD

**Issue by yanlingsishao** [mage-ai/mage-ai#5116]
### Mage version

v0.9.70

### Describe the bug

Sometimes the following errors may occur when executing triggers
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry

    return self._execute(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute

    result = self.block.execute_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/dynamic/child.py", line 183, in execute_sync

    parent_index = dynamic_block_index % count

ZeroDivisionError: integer division or modulo by zero

Stack trace

  File "/usr/local/bin/mage", line 8, in <module>
    sys.exit(app())

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore

  File "/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py", line 163, in start
    start_server(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py", line 773, in start_server
    scheduler_manager.start_scheduler()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 92, in start_scheduler
    proc.start()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py", line 53, in run_scheduler
    LoopTimeTrigger().start()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 14, in start
    self.run()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py", line 11, in run
    schedule_all()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1633, in schedule_all
    PipelineScheduler(r).start()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 157, in func_with_rollback
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 190, in start
    self.schedule()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 157, in func_with_rollback
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 317, in schedule
    self.__schedule_blocks(block_runs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 618, in __schedule_blocks
    job_manager.add_job(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py", line 28, in add_job
    self.queue.enqueue(job_id, target, *args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py", line 121, in enqueue
    self.start_worker_pool()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py", line 198, in start_worker_pool
    self.worker_pool_proc.start()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py", line 351, in poll_job_and_execute
    worker.start()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

  File "/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py", line 117, in wrapper
    return wrapped(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py", line 315, in run
    start_session_and_run(args[1], *args[2], **args[3])

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py", line 15, in start_session_and_run
    results = target(*args)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1170, in run_block
    return ExecutorFactory.get_block_executor(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 46, in retry_func
    logger.warning(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 39, in warning
    self.__send_message('warning', message, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 65, in __send_message
    data['error_stack'] = traceback.format_stack(),
```

**Comment by Ayumi08** [comment]
This issue has been resolved in the latest code in [child.py line 122](https://github.com/mage-ai/mage-ai/blob/master/mage_ai/data_preparation/models/block/dynamic/child.py#L122)

```
if count is not None and count >= 1:
    parent_index = dynamic_block_index % count
...
```

**Comment by csharplus** [comment]
This issue has been resolved with the code changes in [this commitment](https://github.com/mage-ai/mage-ai/commit/9b62bdecadc0030a92bafc2e54defc3ba0b97158#diff-1170785b7e26c41a9c916cdef77eb683dbd64cdb0a99d3941c02e4c3a9ea1924)
