### ISSUE TITLE
[BUG] Unable to use git sync

### ISSUE THREAD

**Issue by renan-pereira-botafogo** [mage-ai/mage-ai#5271]
### Mage version

0.9.72

### Describe the bug

I can't git sync with my remote github repo at all in 0.9.72. It works perfectly in 0.9.71. The error message has no meaning and just prompts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@".

### To reproduce

1. Deploy mage AI using terraform scripts to Google Cloud Run
2. Go to the app settings
3. Configure the SSH connection
4. Hit the "Save repository settings" button
5. Hit the "Synchronize Code" Button

### Expected behavior

Fetch the updated codebase from github

### Screenshots

![image](https://github.com/user-attachments/assets/2d807f6a-31f6-43f1-9bee-496bbe35d146)

### Operating system

Managed instance in GCP Cloud Run.

### Additional context

Detailed error logs from cloud run:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py", line 610, in main
    sync.sync_data()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/sync/git_sync.py", line 40, in sync_data
    self.git_manager.reset_hard(branch=self.branch)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/git/__init__.py", line 235, in wrapper
    asyncio.run(self.check_connection())
  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/local/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/git/__init__.py", line 213, in check_connection
    await check_connection_async(self.repo.git, self.origin.name)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/git/utils.py", line 217, in check_connection_async
    await poll_process_with_timeout(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/git/utils.py", line 201, in poll_process_with_timeout
    raise ChildProcessError(message)
ChildProcessError: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by wangxiaoyou1993** [comment]
@renan-pereira-botafogo do you still have this issue?

**Comment by renan-pereira-botafogo** [comment]
> @renan-pereira-botafogo do you still have this issue?

I locked my mage version on 0.9.71 and it solved my issue. I never tried updating it again. So the issue might still exist?

**Comment by mangobillbay** [comment]
I have a similar problem. Git sync activated and ssh-keys stored as "Git secrets". The first time I sync it works fine, but then the next time it syncs I get the above error. In my case it seems like the SSH-keys (secrets) have been "consumed" and does not work anymore. If I re-enter the ssh keys in the GUI it works the next time (but then stop working after the sync).

Our setup:
Mage version: 0.9.74
Kubernetes setup.
