### ISSUE TITLE
[BUG] Cannot manually run a block from the UI in pipeline editing page on Windows

### ISSUE THREAD

**Issue by tranquochuy645** [mage-ai/mage-ai#5287]
### Mage version

0.9.72

### Describe the bug

Cannot manually run a block from the UI in page on Windows:  http://localhost:6789/pipelines/\<pipeline name\>/edits
- When I click the "Run block" button, the loading indicator start spinning forever, and the code was never executed.
- However, with the same setup, the pipeline can be triggered normally from  http://localhost:6789/pipelines/\<pipeline name\>/triggers 
-I found the error below:
```
ERROR:tornado.application:Uncaught exception GET /websocket/ (::1)
HTTPServerRequest(protocol='http', host='localhost:6789', method='GET', uri='/websocket/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 1051, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\web.py", line 1786, in _execute
    result = await result
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\websocket.py", line 272, in get
    await self.ws_connection.accept_connection(self)
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\websocket.py", line 862, in accept_connection
    await self._accept_connection(handler)
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\websocket.py", line 945, in _accept_connection
    await self._receive_frame_loop()
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\websocket.py", line 1101, in _receive_frame_loop
    await self._receive_frame()
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\websocket.py", line 1192, in _receive_frame
    await handled_future
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 285, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\websocket_server.py", line 305, in on_message
    await self.__execute_block(
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\websocket_server.py", line 480, in __execute_block
    code = add_execution_code(
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\utils\output_display.py", line 289, in add_execution_code
    code_content = __interpolate_code_content('execute_custom_code.py', replacements)
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\utils\output_display.py", line 202, in __interpolate_code_content
    content = re.sub(placeholder_pattern, str(replacement), content)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\re.py", line 209, in sub      
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\re.py", line 326, in _subx    
    template = _compile_repl(template, pattern)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \U at position 3
ERROR:tornado.application:Exception in callback functools.partial(<function WebSocketProtocol._run_callback.<locals>.<lambda> at 0x0000017D609EA950>, <Task finished name='Task-175' coro=<WebSocketServer.on_message() done, defined at C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\websocket_server.py:185> exception=error('bad escape \\U at position 3')>)
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 1051, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\ioloop.py", line 738, in _run_callback
    ret = callback()
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\tornado\websocket.py", line 639, in <lambda>
    self.stream.io_loop.add_future(result, lambda f: f.result())
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\websocket_server.py", line 305, in on_message
    await self.__execute_block(
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\websocket_server.py", line 480, in __execute_block
    code = add_execution_code(
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\utils\output_display.py", line 289, in add_execution_code
    code_content = __interpolate_code_content('execute_custom_code.py', replacements)
  File "C:\Users\username\Desktop\projectname\.venv\lib\site-packages\mage_ai\server\utils\output_display.py", line 202, in __interpolate_code_content
    content = re.sub(placeholder_pattern, str(replacement), content)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\re.py", line 209, in sub      
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\re.py", line 326, in _subx    
    template = _compile_repl(template, pattern)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \U at position 3
```

### To reproduce

1.Go to http://localhost:6789/pipelines/\<pipeline name\>/edits
2.Click "Run block" on any block

### Screenshots

![image](https://github.com/user-attachments/assets/58570be2-5b3e-4ab9-a8be-7b0a0690c87e)

### Operating system

 - python venv 3.10 , 3.11, 3.12 
 - Windows 10
 - Browser: Firefox, Chrome, Edge

### Additional context

- Everything works fine in a docker container, but not with mage installed through pip
- I have tried different python versions, setup a venv but mage can't work if it's Windows

**Comment by lhbeers** [comment]
myself as well

**Comment by lhbeers** [comment]
same here - can run the sample end to end, but not the block. kills my use case to attract internal resources.
pyenv 3.12.7
