### ISSUE TITLE
Pipeline AI Beta feature error

### ISSUE THREAD

**Issue by SahithPalika** [mage-ai/mage-ai#5323]
### Mage version

 v0.9.73

### Describe the bug

When I try to create a pipeline using AI which is now in beta mode, I am uanble to create one. I face the following issue - "**'APIConnectionError' object has no attribute 'choices'**" 

I tried with the docker images of current version and v0.9.72 docker images as well. Still no luck.
![image](https://github.com/user-attachments/assets/ce9f19b7-d851-41c8-aade-736306aac7f0)

Error -

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute

    result = await result

  File "/home/src/mage_ai/server/api/v1.py", line 64, in post

    return await execute_operation(self, resource)

  File "/home/src/mage_ai/api/views.py", line 70, in execute_operation

    raise err

  File "/home/src/mage_ai/api/views.py", line 63, in execute_operation

    response = await base_operation.execute()

  File "/home/src/mage_ai/api/operations/base.py", line 93, in execute

    result = await self.__executed_result()

  File "/home/src/mage_ai/api/operations/base.py", line 481, in __executed_result

    return await self.__create_or_index()

  File "/home/src/mage_ai/api/operations/base.py", line 534, in __create_or_index

    result = await self.__resource_class().process_create(

  File "/home/src/mage_ai/api/resources/BaseResource.py", line 212, in process_create

    raise err

  File "/home/src/mage_ai/api/resources/BaseResource.py", line 200, in process_create

    res = await res

  File "/home/src/mage_ai/api/resources/PipelineResource.py", line 448, in create

    llm_resource = await LlmResource.create(llm_payload, user, **kwargs)

  File "/home/src/mage_ai/api/resources/LlmResource.py", line 8, in create

    response = await Generator.generate(payload.get('use_case'), payload.get('request'))

  File "/home/src/mage_ai/ai/generator.py", line 36, in generate

    return await LLMPipelineWizard().async_generate_pipeline_from_description(

  File "/home/src/mage_ai/ai/llm_pipeline_wizard.py", line 387, in async_generate_pipeline_from_description

    await asyncio.gather(*block_tasks)

  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup

    future.result()

  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 232, in __step

    result = coro.send(None)

  File "/home/src/mage_ai/ai/llm_pipeline_wizard.py", line 360, in __async_generate_blocks

    block = await self.async_generate_block_with_description(block_description, upstream_blocks)

  File "/home/src/mage_ai/ai/llm_pipeline_wizard.py", line 303, in async_generate_block_with_description

    function_params = await self.client.find_block_params(block_description)

  File "/home/src/mage_ai/ai/openai_client.py", line 192, in find_block_params

    arguments = response.choices[0].message.tool_calls[0].function.arguments

AttributeError: 'APIConnectionError' object has no attribute 'choices'

Stack trace ([hide stack trace](http://3.16.76.234:6789/overview?tab=today#))

  File "/home/src/mage_ai/cli/main.py", line 320, in      app()

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__     return get_command(self)(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__     return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778, in main     return _main(

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main     rv = self.invoke(ctx)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke     return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke     return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke     return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper     return callback(**use_params)  # type: ignore

  File "/home/src/mage_ai/cli/main.py", line 147, in start     start_server(

  File "/home/src/mage_ai/server/server.py", line 801, in start_server     asyncio.run(

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run     return loop.run_until_complete(main)

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete     self.run_forever()

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever     self._run_once()

  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 133, in _run_once     handle._run()

  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run     self._context.run(self._callback, *self._args)

  File "/home/src/mage_ai/server/server.py", line 720, in main     get_messages(

  File "/home/src/mage_ai/server/subscriber.py", line 14, in get_messages     message = client.get_iopub_msg(timeout=1)

  File "/usr/local/lib/python3.10/site-packages/jupyter_client/utils.py", line 27, in wrapped     return loop.run_until_complete(future)

  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 92, in run_until_complete     self._run_once()

  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 133, in _run_once     handle._run()

  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run     self._context.run(self._callback, *self._args)

  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 307, in __wakeup     self.__step(exc)

  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 234, in __step     result = coro.throw(exc)

  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1791, in _execute     self._handle_request_exception(e)

  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1848, in _handle_request_exception     self.send_error(500, exc_info=sys.exc_info())

  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1294, in send_error     self.write_error(status_code, **kwargs)

  File "/home/src/mage_ai/server/api/base.py", line 65, in write_error     errors = traceback.format_stack()

### Operating system

Ubuntu 22.04

**Comment by SahithPalika** [comment]
@tk26 Hi, I have seen you as one of the active contributors to the platform, can you confirm if this feature is still in developing state and needs some time to fully evolve or the issue I am facing is something unsual?

**Comment by wangxiaoyou1993** [comment]
You can downgrade your version to 0.9.72. It could be a bug in 0.9.73

**Comment by wangxiaoyou1993** [comment]
@matrixstone can you take a look?

**Comment by SahithPalika** [comment]
Hi wang. I later tried with 0.9.72 but still no luck. However I moved on with deploying using docker image 0.9.73 and it worked.

**Comment by SahithPalika** [comment]
This is what I am getting from the logs.


Connection error.
INFO:openai._base_client:Retrying request to /chat/completions in 0.798942 seconds
INFO:openai._base_client:Retrying request to /chat/completions in 1.640493 seconds
Unable to generate ChatCompletion response
Exception: Connection error.
Connection error.
ERROR:mage_ai.api.logging:[2024-08-14T08:22:59.471587][api.views] [2024-08-14 08:22:59.471563] [ERROR] POST /pipelines [user: N/A]: 'APIConnectionError' object has no attribute 'choices'

**Comment by joelvh** [comment]
I'm on v0.9.73 and specified the API key in the settings page. But it appears that api key isn't being used? (Same issue when trying to create a block.)

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/aa72a603-6881-4289-9030-ddd907b3e260">

<img width="742" alt="image" src="https://github.com/user-attachments/assets/76c7915c-3833-4cb4-8b0f-8c28e5dc2262">

<img width="605" alt="image" src="https://github.com/user-attachments/assets/285f755a-5454-41d6-9ecf-e4cce495199a">

**Comment by SahithPalika** [comment]
Hi @joelvh 
I assume that you are using docker image to deploy mage as I have faced the same issue previously.
If you are using a docker image, run your container by passing your key as an environment variable. 
docker run -e OPENAI_API_KEY= BGuuFJ _image

**Comment by matrixstone** [comment]
Hi @SahithPalika Thank you for reporting the issue!

In your case, openAI returns `APIConnectionError ` but we still try to access the response, that is causing the error. I put up a fix by checking the response type firstly with retry to avoid that: https://github.com/mage-ai/mage-ai/pull/5375.

**Comment by joelvh** [comment]
thanks @SahithPalika - that worked. Strange though, that the project settings pop up in a modal telling me I have to specify an OpenAI API key. I click "Save" without entering an API key and it still runs and generates an AI pipeline now.

I wonder if that's a UX error because it's an environment variable, not a project setting now?
