### ISSUE TITLE
[BUG] Installation fails with Python 3.12: "ValueError: not enough values to unpack"

### ISSUE THREAD

**Issue by timmapuramreddy** [mage-ai/mage-ai#5386]
### Mage version

0.9.73

### Description:
I'm encountering an issue when installing `mage-ai` with Python 3.12. The installation process fails with the following error:

```plaintext
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [20 lines of output]
Traceback (most recent call last):
File "/path/to/python3.12/...", line 353, in <module>
...
File "/private/var/folders/.../build_meta.py", line 205, in get_compiler_settings
ValueError: not enough values to unpack (expected 2, got 0)

### To reproduce

1.	Create a Python 3.12 virtual environment.
2.	Run the following command:
pip install "mage-ai[all]"

The installation fails with the above error.
Getting requirements to build wheel … error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [20 lines of output]
Traceback (most recent call last):
File “/path/to/python3.12/…”, line 353, in 
…
File “/private/var/folders/…/build_meta.py”, line 205, in get_compiler_settings
ValueError: not enough values to unpack (expected 2, got 0)

### Expected behavior

The installation should succeed as it does with Python 3.11.


### Screenshots

_No response_

### Operating system

OS: macOS
Python version: 3.12.0
Mage-ai version: Latest (attempted install with pip)

### Additional context

Please advise if this is a known issue or if a patch is in progress for Python 3.12 compatibility.

**Comment by csharplus** [comment]
@timmapuramreddy this issue was fixed with https://github.com/mage-ai/mage-ai/pull/5393. Please try the latest mage open-source version, and see if it works for you.

**Comment by csharplus** [comment]
Installing Mage with Python 3.12 is now supported.
