### ISSUE TITLE
[BUG] Block fails to update im metadatabase when running time is greater then idle_in_transaction_session_timeout

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#5408]
### Mage version

0.9.73

### Describe the bug

We are using PostgreSQL as  metadata storage for MageAI, our current orchestration tool. In the orchestrated pipelines, we have some blocks that can run for hours, in extreme cases, up to one day, as they orchestrate the processing of a massive amount of data.

What has been happening is that when a pipeline block runs for more than an hour, it ends up returning an idle-transaction error, and Mage is unable to update the block to the "SUCCESS" status, so the block restarts.

It was found that the idle_in_transaction_session_timeout parameter is configured for 1 hour on the instance in use.

Is it possible to change the behaviour of thoses sesssions opened by blocks to update block status in mageAI metdatabase?
I

### To reproduce

Create a block that runs for more time that set in `idle_in_transaction_session_timeout` parameter in mage database.

### Screenshots

![image](https://github.com/user-attachments/assets/04233b46-1f5b-4910-9c1f-bae64de9e067)
![image](https://github.com/user-attachments/assets/0015f5d7-4ceb-4a37-b44f-b6d00f0cf667)

**Comment by haithem-souala** [comment]
Same here with the 0.9.79 on GKE

**Comment by haithem-souala** [comment]
Failed to update block run status to completed for block
```
Error

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl

    self.engine.dialect.do_commit(self.connection)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit

    dbapi_connection.commit()

sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1413, in __update_block_run_status

    block_run.update(**update_kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/models/base.py", line 93, in update

    raise e

  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/models/base.py", line 90, in update

    self.session.commit()

  File "<string>", line 2, in commit

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1454, in commit

    self._transaction.commit(_to_root=self.future)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 839, in commit

    trans.commit()

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2469, in commit

    self._do_commit()

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2659, in _do_commit

    self._connection_commit_impl()

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2630, in _connection_commit_impl

    self.connection._commit_impl()

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1096, in _commit_impl

    self._handle_dbapi_exception(e, None, None, None, None)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception

    util.raise_(

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_

    raise exception

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl

    self.engine.dialect.do_commit(self.connection)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit

    dbapi_connection.commit()

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error

(Background on this error at: https://sqlalche.me/e/14/e3q8)

Stack trace

  File "/usr/local/bin/mage", line 8, in <module>
    sys.exit(app())

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(

  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore

  File "/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py", line 261, in run
    ExecutorFactory.get_block_executor(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 739, in execute
    self.__update_block_run_status(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1416, in __update_block_run_status
    self.logger.exception(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 30, in exception
    self.__send_message('exception', message, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py", line 65, in __send_message
    data['error_stack'] = traceback.format_stack()

```
