### ISSUE TITLE
[BUG] Api cannot handle JSON body where body is an array

### ISSUE THREAD

**Issue by stefan-sessions** [mage-ai/mage-ai#5414]
### Mage version

v0.9.73

### Describe the bug

if an API trigger is called with a JSON payload that is an array at the top level, the run does not start and does not appear at all in the UI.
Several critical external systems use this format and cannot be adapted to use others, for example, HubSpot sends all webhooks with an array at the top level, as stated in their documentation [here](https://developers.hubspot.com/docs/api/webhooks#:~:text=As%20shown%20above%2C%20you%20should%20expect%20to%20receive%20an%20array%20of%20objects%20in%20a%20single%20request)

Initially posted here: https://mageai.slack.com/archives/C03HTTWFEKE/p1726000787767229

### To reproduce

Example stripped back code:
```
import requests
trigger_url="https://..."
payload=[{"id":1,"value":"yes"}]
resp = requests.post(url,json=payload)

```
This returns `resp.status_code==200` but the `resp.json()` indicates the problem - it's expecting a dictionary but is receiving a list:
```
{'error': {'code': 500,
  'errors': ['  File "/usr/local/bin/mage", line 8, in <module>\n    sys.exit(app())\n',
   '  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n',
   '  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__\n    return self.main(*args, **kwargs)\n',
   '  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778, in main\n    return _main(\n',
   '  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main\n    rv = self.invoke(ctx)\n',
   '  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n',
   '  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n',
   '  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke\n    return __callback(*args, **kwargs)\n',
   '  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n',
   '  File "/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py", line 147, in start\n    start_server(\n',
   '  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py", line 813, in start_server\n    asyncio.run(\n',
   '  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n',
   '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n',
   '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n',
   '  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 133, in _run_once\n    handle._run()\n',
   '  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run\n    self._context.run(self._callback, *self._args)\n',
   '  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py", line 732, in main\n    get_messages(\n',
   '  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/subscriber.py", line 14, in get_messages\n    message = client.get_iopub_msg(timeout=1)\n',
   '  File "/usr/local/lib/python3.10/site-packages/jupyter_client/utils.py", line 27, in wrapped\n    return loop.run_until_complete(future)\n',
   '  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 92, in run_until_complete\n    self._run_once()\n',
   '  File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 133, in _run_once\n    handle._run()\n',
   '  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run\n    self._context.run(self._callback, *self._args)\n',
   '  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 232, in __step\n    result = coro.send(None)\n',
   '  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1791, in _execute\n    self._handle_request_exception(e)\n',
   '  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1848, in _handle_request_exception\n    self.send_error(500, exc_info=sys.exc_info())\n',
   '  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1294, in send_error\n    self.write_error(status_code, **kwargs)\n',
   '  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/api/base.py", line 65, in write_error\n    errors = traceback.format_stack()\n'],
  'exception': "'list' object has no attribute 'get'",
  'message': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute\n    result = method(*self.path_args, **self.path_kwargs)\n  File "/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/api/triggers.py", line 33, in post\n    payload = self.get_payload()\n  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/api/base.py", line 118, in get_payload\n    payload = payload.get(key, {})\nAttributeError: \'list\' object has no attribute \'get\'\n'},
 'url_parameters': {'pipeline_schedule_id': '148',
  'token': 'xxxx'}}
```

### Expected behavior

Expected a call to the trigger api endpoint to trigger a pipeline run, but nothing appears in the UI and a backend error occurs

### Operating system

- GCP
- Cloud Run

**Comment by tommydangerous** [comment]
Thank you for adding. How urgent is this feature request?

**Comment by acamara-res** [comment]
Could you please provide an estimated date for when this issue might be resolved?

Thank you for your time and effort in maintaining this project. Your work is greatly appreciated!
