### ISSUE TITLE
[BUG] error adding dbt block from file

### ISSUE THREAD

**Issue by TomAtGithub** [mage-ai/mage-ai#5612]
### Mage version

0.9.75

### Describe the bug

Error while adding a dbt block to a pipeline.
- With "add new block v2" enabled or disabled
- running in python or docker
- with dbt installed or not

### To reproduce

1. set up mage-ai with docker-compose as described in the docks: https://docs.mage.ai/getting-started/setup#docker-compose
2.  create new dbt file: right click on dbt in directury tree --> new file -> my_first_dbt_model.sql
3. edit pipeline example_pipeline
4. add dbt model from file: hover over block --> click dbt model --> Select dbt model or snapshot file --> dbt/my_first_dbt_model.sql
5. Shows error:

>Error
>
>expected str, bytes or os.PathLike object, not NoneType

### Expected behavior

The selected dbt model is added as block to the pipeline

### Screenshots

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/e0ef15f0-69c6-421f-bb72-ba85dac613b8" />

### Operating system

- mac os 14.5 (23F79) with M3 chip

### Additional context

Stack trace:

```
ERROR:mage_ai.api.logging:[2024-12-12T12:30:04.359334][api.views] [2024-12-12 12:30:04.359313] [ERROR] POST /pipelines/super_cloud/blocks [user: N/A]: expected str, bytes or os.PathLike object, not NoneType
ERROR:tornado.application:Uncaught exception POST /api/pipelines/super_cloud/blocks?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (127.0.0.1)
HTTPServerRequest(protocol='http', host='0.0.0.0:6789', method='POST', uri='/api/pipelines/super_cloud/blocks?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/server/api/v1.py", line 36, in post
    return await execute_operation(self, resource, **dict(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/views.py", line 70, in execute_operation
    raise err
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/views.py", line 63, in execute_operation
    response = await base_operation.execute()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/operations/base.py", line 93, in execute
    result = await self.__executed_result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/operations/base.py", line 481, in __executed_result
    return await self.__create_or_index()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/operations/base.py", line 534, in __create_or_index
    result = await self.__resource_class().process_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/resources/BaseResource.py", line 212, in process_create
    raise err
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/resources/BaseResource.py", line 200, in process_create
    res = await res
          ^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/api/resources/BlockResource.py", line 222, in create
    block = Block.create(
            ^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1167, in create
    block = BlockFactory.block_class_from_type(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 442, in __init__
    self.configuration = configuration
    ^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 480, in configuration
    self._configuration = self.clean_file_paths(x) if x else x
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/data_preparation/models/block/platform/mixins.py", line 72, in clean_file_paths
    project_path = get_selected_directory_from_file_path(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anon/Library/Caches/pypoetry/virtualenvs/mage-ai-test-RzTzxdp3-py3.12/lib/python3.12/site-packages/mage_ai/data_preparation/models/block/platform/utils.py", line 98, in get_selected_directory_from_file_path
    path = os.path.dirname(project_full_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 181, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by kylejbrk** [comment]
I am also getting this error

**Comment by kylejbrk** [comment]
Found the issue you need to make sure your dbt is configured properly with profiles.yml and dbt_project.yml
