### ISSUE TITLE
Cannot pip install

### ISSUE THREAD

**Issue by archiewood** [mage-ai/mage-ai#870]
```
pip install mage-ai
Collecting mage-ai
  Downloading mage_ai-0.2.9-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 7.9 MB/s eta 0:00:00
Requirement already satisfied: joblib>=1.1.0 in /opt/homebrew/lib/python3.9/site-packages (from mage-ai) (1.1.0)
Requirement already satisfied: click==8.1.3 in /opt/homebrew/lib/python3.9/site-packages (from mage-ai) (8.1.3)
Collecting Flask~=1.1.2
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 2.8 MB/s eta 0:00:00
Collecting itsdangerous~=1.1.0
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting pyarrow==6.0.0
  Downloading pyarrow-6.0.0-cp39-cp39-macosx_11_0_arm64.whl (13.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 8.5 MB/s eta 0:00:00
Collecting pyyaml~=6.0
  Using cached PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting jupyter-server-proxy==3.2.1
  Downloading jupyter_server_proxy-3.2.1-py3-none-any.whl (35 kB)
Collecting asyncio==3.4.3
  Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: pytz==2022.1 in /opt/homebrew/lib/python3.9/site-packages (from mage-ai) (2022.1)
Requirement already satisfied: zipp==3.8.0 in /opt/homebrew/lib/python3.9/site-packages (from mage-ai) (3.8.0)
Requirement already satisfied: python-dateutil==2.8.2 in /opt/homebrew/lib/python3.9/site-packages (from mage-ai) (2.8.2)
Collecting requests==2.27.0
  Downloading requests-2.27.0-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 2.1 MB/s eta 0:00:00
Collecting tables==3.7.0
  Downloading tables-3.7.0.tar.gz (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 8.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /var/folders/l7/m69bgsp16830cvfm6973p2h00000gn/T/H5closeleexy1dq.c:2:5: error: implicit declaration of function 'H5close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          H5close();
          ^
      1 error generated.
      cpuinfo failed, assuming no CPU features: No module named 'cpuinfo'
      * Using Python 3.9.13 (main, Aug  7 2022, 01:19:39)
      * Found cython 0.29.32
      * USE_PKGCONFIG: True
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by wangxiaoyou1993** [comment]
Thanks for creating this issue! We'll fix it ASAP.
Meanwhile, could you try running `brew install HDF5` first and then installing mage-ai to see whether this issue is fixed?

**Comment by wangxiaoyou1993** [comment]
@archiewood We just pushed a fix and a new version. You can install the latest version now.

**Comment by wangxiaoyou1993** [comment]
@archiewood I'll close this issue. Let me know if you still have problems installing the library.

**Comment by archiewood** [comment]
I *think* I've managed to install successfully now.

But `mage start my-mage-project` errors out
```
mage start my-mage-project
Traceback (most recent call last):
  File "/opt/homebrew/bin/mage", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/mage_ai/command_line.py", line 47, in main
    from mage_ai.server.server import main as start_server
  File "/opt/homebrew/lib/python3.9/site-packages/mage_ai/server/server.py", line 1, in <module>
    from mage_ai.data_preparation.models.block import Block
  File "/opt/homebrew/lib/python3.9/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 5, in <module>
    from mage_ai.data_cleaner.shared.utils import is_dataframe
  File "/opt/homebrew/lib/python3.9/site-packages/mage_ai/data_cleaner/shared/utils.py", line 2, in <module>
    from mage_ai.data_cleaner.transformer_actions.constants import CURRENCY_SYMBOLS
  File "/opt/homebrew/lib/python3.9/site-packages/mage_ai/data_cleaner/transformer_actions/constants.py", line 3, in <module>
    import pandas as pd
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by archiewood** [comment]
I take it back - I uninstalled and reinstalled numpy, and - it worked
