### ISSUE TITLE
Cannot Create New Pipeline

### ISSUE THREAD

**Issue by connorjoleary** [mage-ai/mage-ai#968]
I have a project running with:
- `mage start`
- mage version `0.3.4`
- windows machine using WSL

I seem to be unable to create a new pipeline. I can press the new pipeline button on the UI and refresh the page so it appears, but then I get the error:
```
Traceback (most recent call last):

  File "/mnt/c/Users/path_to/venv/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute

    result = method(*self.path_args, **self.path_kwargs)

  File "/mnt/c/Users/path_to/venv/lib/python3.7/site-packages/mage_ai/server/server.py", line 111, in get

    pipeline = Pipeline.get(pipeline_uuid)

  File "/mnt/c/Users/path_to/venv/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 137, in get

    return Pipeline(uuid)

  File "/mnt/c/Users/path_to/venv/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 38, in __init__

    self.load_config_from_yaml()

  File "/mnt/c/Users/path_to/venv/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 247, in load_config_from_yaml

    self.load_config(self.get_config_from_yaml())

  File "/mnt/c/Users/path_to/venv/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 269, in load_config

    blocks = [build_shared_args_kwargs(c, Block) for c in self.block_configs]

TypeError: 'NoneType' object is not iterable

'NoneType' object is not iterable
```

**Comment by tommydangerous** [comment]
👀 We’re looking into this. Will give you an update ASAP.

**Comment by connorjoleary** [comment]
Thank you!
Update from my side. Adding a step to the blocks list in the medadata.yaml file fixes it.

**Comment by tommydangerous** [comment]
Thank you for sharing. We’ve identified the problem and are currently working on a long term fix.

Thank you for your patience!

**Comment by connorjoleary** [comment]
Thank you! Also loved the talk you gave here: https://www.youtube.com/watch?v=6Iyt9Wip3C4

**Comment by tommydangerous** [comment]
@connorjoleary we fixed this 3 days ago.

If for some miraculous reason it happens again, please ping me here or on Slack (www.mage.ai/chat)
