### ISSUE TITLE
Error occurred on demo

### ISSUE THREAD

**Issue by emptyfist** [mage-ai/mage-ai#997]
Well, I visited [demo](http://demo.mage.ai/) and found out error as followings.

```
[load_data] Executing data_loader block...

[load_data] DONE

[proud_snowflake] Executing data_loader block...

[proud_snowflake] DONE

Pipeline default_pipeline execution failed with error:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/websocket.py", line 87, in run_pipeline

    pipeline.execute_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipeline.py", line 230, in execute_sync

    run_blocks_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 139, in run_blocks_sync

    block.execute_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 442, in execute_sync

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 398, in execute_sync

    output = self.execute_block(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 599, in execute_block

    outputs = execute_sql_code(self, custom_code or self.content)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 18, in execute_sql_code

    config_file_loader = ConfigFileLoader(config_path, config_profile)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/config.py", line 275, in __init__

    self.config = yaml.full_load(config_file)[profile]

KeyError: None
```

**Comment by tommydangerous** [comment]
There were a lot of test blocks added by others that failed when executed.

I deleted them. The pipeline now looks like this:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1066980/188573439-912714e0-321e-4061-9e0c-028e3981efd0.png">

Please try it again. Sorry for the inconvenience.
